version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env 
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - redis
      - minio
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  celery:
    build: ./backend
    container_name: celery
    command: celery -A src.middleware.video_processing.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      - backend
      - redis
      - minio
    volumes:
      - ./backend:/app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio-diplom
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  frontend:
    build: ./car_tracking
    container_name: frontend
    restart: unless-stopped
    ports:
      - "4173:4173"
    depends_on:
      - backend
    volumes:
      - ./car_tracking:/app

volumes:
  minio_data: 